<?php $current_url = Mage::helper('core/url')->getCurrentUrl(); ?>
<div id="video">
<video id="lily-video1" controls="controls" poster="http://www.lily-collection.com/media/wysiwyg/spring-vedio-poster.jpg" width="1280" height="720">
	<source src="http://www.lily-collection.com/media/video/FF_LILY_20130815_VIDEO_LAMP_V1.mp4" type="video/mp4" />
	<source src="http://www.lily-collection.com/media/video/FF_LILY_20130815_VIDEO_LAMP_V1.webm" type="video/webm" />
	<object type="application/x-shockwave-flash" data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" width="1280" height="720">
		<param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
		<param name="allowFullScreen" value="true" />
		<param name="wmode" value="transparent" />
		<param name="flashVars" value="config={'playlist':['http%3A%2F%2Fwww.lily-collection.com%2Fmedia%2Fwysiwyg%2Fvideo.jpg',{'url':'http%3A%2F%2Fwww.lily-collection.com%2Fmedia%2Fvideo%2FFF_LILY_20130815_VIDEO_LAMP_V1.mp4','autoPlay':false}]}" />
		<img alt="Lily商务时装官网001" src="http://www.lily-collection.com/media/wysiwyg/spring-vedio-poster.jpg" width="1280" height="720" title="No video playback capabilities, please download the video below" />
	</object>
</video>

<video id="lily-video3" controls="controls" poster="http://www.lily-collection.com/media/wysiwyg/spring-vedio-poster.jpg" width="1280" height="720" style="display:none">
	<source src="http://www.lily-collection.com/media/video/LILY_MAKING_OF_MASTER.webmhd.mp4" type="video/mp4" />
	<source src="http://www.lily-collection.com/media/video/LILY_MAKING_OF_MASTER.webmhd.webm" type="video/webm" />
	<object type="application/x-shockwave-flash" data="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" width="1280" height="720" class="lily-video3">
		<param name="movie" value="http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf" />
		<param name="allowFullScreen" value="true" />
		<param name="wmode" value="transparent" />
		<param name="flashVars" value="config={'playlist':['http%3A%2F%2Fwww.lily-collection.com%2Fmedia%2Fwysiwyg%2Fvideo.jpg',{'url':'http%3A%2F%2Fwww.lily-collection.com%2Fmedia%2Fvideo%2FLILY_MAKING_OF_MASTER.webmhd.mp4','autoPlay':false}]}" />
		<img alt="Lily商务时装官网001" src="http://www.lily-collection.com/media/wysiwyg/spring-vedio-poster.jpg" width="1280" height="720" title="No video playback capabilities, please download the video below" />
	</object>
</video>
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function($){


$('#video-img').click(function(){
	$(this).hide();
	$("#lily-video1").show();
	$("#lily-video1").get(0).play();
	$("#lily-video1").get(0).play();
});
//$("#lily-video1").hide();

$("#lily-video1").bind("ended", function() {
	$(this).hide();
	$("#lily-video3").show();
	$(".lily-video3").show();
	$("#lily-video3").get(0).play();
	$(".lily-video3").get(0).play();
});

$("#lily-video3").bind("ended", function() {
	$(this).hide();
	$("#lily-video1").show();
	//$("#lily-video1").get(0).play();
});
});
</script>
</div>
<div id="kv" class="window">

<div class = 'container'>
			
			<div class = 'iosSlider'>
			
				<div class = 'slider'>

					<div class = 'item' dataurl = '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'>
					
						<!--<span class="text1">F/W 2003 1/3</span>-->
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/kv/spring-kv1.jpg" alt="Lily商务时装官网002" />
					</div>
					<div class = 'item' dataurl = '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'>
						<!--<span class="text1">F/W 2003 1/3</span>-->
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/kv/spring-kv2.jpg"  alt="Lily商务时装官网003" />
					</div>
					<div class = 'item' dataurl = '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'>
						<!--<span class="text1">F/W 2003 1/3</span>-->
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/kv/spring-kv3.jpg" alt="Lily商务时装官网004" />
					</div>

				
				</div>
				
				<div class = 'prevContainer'>
					<div class = 'prev'>Prev slide</div>
				</div>
				
				<div class = 'nextContainer'>
					<div class = 'next'>Next slide</div>
				</div>
				
				<div class = 'selectorsBlock'>
				
					<div class = 'selectors'>
						<div class = 'item first selected'></div>
						<div class = 'item'></div>
						<div class = 'item'></div>

					</div>
					
				</div>
					
					
			
			</div>
			
				<!-- Add Jia This Share -->
			<div class="share-slider" onmouseover="setShare('','', '');">                 
			
		
			
				<div id="ckepop" class="ckepop">      
				
				<div id="open-share" class="open-share">
					<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
				</div>
				<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
				<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
				</div>
		
			</div>
		<!-- End -->
						
		</div>


</div>

<div id="brand"  class="window">
<div class="brand-txt" id="movetxt">
<!-- Add Jia This Share -->
		<div onmouseover="setShare('品牌故事', '<?php echo $current_url; ?>', '', '现代艺术范儿，是Lily品牌的创作之源。设计师将现代艺术与民俗、摩登时代、超现实主义、拜占庭艺术等潮流趋势相结合，创造出独特的OL商务时尚。');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open_b.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo_b.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent_b.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
<h2>Brand</h2>

<p><?php echo $this->__('As an avant-garde of office-chic brand, Lily combines business and style with perception, flatters women with simple yet graceful styling, and contributes to their confidence with beauty and elegancy.')?></p>

<p><?php echo $this->__('Lily has staged several fashion shows on international fashion extravaganza, including Milan Fashion Week, German CPD, and was the winner of the New Designer Award at the former. We believe it is already safe to say that Lily has turned quite a few heads from the world fashion industry.')?></p>

<p><?php echo $this->__('Strength, feminity, modernity and vivacity are at the core of Lily’s DNA. Lily designers seek inspiration from modern artistry and accessorize with surrealism, modernism and Byzantine arts, creating a unique business chic that is “no more and no less” for urban ladies.')?></p>

<p><?php echo $this->__('Up till now, Lily has branched over 500 stores in more than 220 cities of China, plus more than 50 stores in Russia, Saudi Arabia, Thailand, Malaysia and Dubai. As a leading brand of female office-chic fashion, Lily has proven itself to be worthy.')?></p>

</div>
</div>

<div id="vision"  class="window">
	<div class="left zoom grid-9">
		<img alt="Lily商务时装视觉001" src="<?php echo $this->getSkinUrl('images/spring2014/vision-zoom-spring.jpg') ?>"/>
		
		<!-- Add Jia This Share -->
		<div onmouseover="setShare('形象大片', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/spring2014/vision-zoom-spring.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
	
	</div>
	<div class="right grid-3">
		<div class="copy">
			<div class="copy-inner">
				<a href="campaign2014spring.html" class="link1">形象大片 LOOK BOOK</a>
				<a href="street-look-book2014spring.html" class="link2">街拍look STREET SNAPS</a>
			</div>
		</div>
		<div class="move-right-img">
		<!-- Add Jia This Share -->
		<div onmouseover="setShare('街拍look', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/spring2014/vision-moveright-spring.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
			<img alt="Lily商务时装视觉002" src="<?php echo $this->getSkinUrl('images/spring2014/vision-moveright-spring.jpg') ?>"/>
		</div>
	</div>


</div>
<div id="new"  class="window">
	<div class="left grid-6">
		<div class="grid-3 move-right-img">
			<!-- Add Jia This Share -->
		<div onmouseover="setShare('潮流趋势', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/spring2014/new-moveright-spring.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
			<img alt="Lily商务时装新品001" src="<?php echo $this->getSkinUrl('images/spring2014/new-moveright-spring.jpg') ?>"/>
		</div>
		<div class="grid-3 copy">
			<div class="copy-inner">
				<a href="trend2014spring.html" class="link1 link3">潮流趋势 TREND FORECAST</a>
				<a href="collection/jianianhua.html" class="link4">搭配推荐 COLLECTION</a>
			</div>
		</div>
		<div class="grid-6">
		<!-- Add Jia This Share -->
		<img alt="Lily商务时装新品002" src="<?php echo $this->getSkinUrl('images/spring2014/new-grid6-spring.jpg') ?>"/>
		<div onmouseover="setShare('潮流趋势', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/spring2014/new-grid6-winter.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
		</div>
	</div>
	<div class="right grid-6 move-left-img">
	<!-- Add Jia This Share -->
		<div onmouseover="setShare('搭配推荐', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/spring2014/new-moveleft-spring.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
		<img alt="Lily商务时装新品003" src="<?php echo $this->getSkinUrl('images/spring2014/new-moveleft-spring.jpg') ?>"/>
	</div>
</div>

<div id="club"  class="window">
	<div class="left grid-3">
	<?php echo $this->getChildHtml('customer_form_login_mini') ?>
	
	
	</div>
	<div class="right zoom grid-9">
		<img alt="Lily商务时装会员001" src="<?php echo $this->getSkinUrl('images/club-zoom.jpg') ?>"/>
		
		<div id="share-button">
			<img src="<?php echo $this->getSkinUrl('images/share_button.png') ?>"/>
		</div>
	
	</div>



</div>
<div id="store"  class="window">

	<div class="left grid-6">

	</div>
	<div class="right grid-6">
	<?php $_province = Mage::getSingleton('core/session')->getSprovince(); ?>
	<?php if($_province != ""):?>
	<?php $citys = Mage::helper('lilystoremap')->getAllCityByProvince($_province); ?>
	<?php endif; ?>
	<?php $provinces = Mage::helper('lilystoremap')->getAllProvince(); ?>
	<div class="store-search">
		<div class="by-detail">
		
			<span class="h1"><span>Store</span>门店</span>
			<div class="input-box widther">
				<label><?php echo $this->__('Country'); ?></label>
				<div class="input-box">
					<select class="selected search-city">
						<option value=""><?php echo $this->__('中国'); ?></option>
					</select>
				</div>
			</div>
			
			<div class="input-box widther">
				<label><?php echo $this->__('Province'); ?></label>
				<div class="input-box">
					<select class="selected search-city" id="province">
						<option value=""><?php echo $this->__('Please Choose')?></option>
						<?php foreach($provinces as $province): ?>
							<option value="<?php echo $province; ?>" <?php if($_province == $province) echo "selected = 'select'"; ?>><?php echo $province; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
			
			
			<div class="input-box widther">
				<label><?php echo $this->__('City'); ?></label>
				<div class="input-box">
					<select class="selected search-city" id="city">
						<?php if($_province != ""):?>
							<?php foreach($citys as $city): ?>
								<option value="<?php echo $city; ?>"><?php echo $city; ?></option>
							<?php endforeach; ?>
						<?php else:?>
							<option value=""><?php echo $this->__('Please Choose Province First')?></option>
						<?php endif; ?>
					</select>
				</div>
			</div>
			
			<div class="action">
				<button class="button" title="Submit" type="button"><span><span><?php echo $this->__('Go'); ?></span></span></button>
			</div>
		</div>
	</div>
	
	</div>

</div>
<div id="timeline"  class="window">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('timeline')->toHtml(); ?>
</div>
<script type="text/javascript">
	jQuery(document).ready(function($){
	
		$('#province').change(function(){
			$.ajax({
				url:'<?php echo $this->getUrl('storemap/index/getCitysByProvince')?>',
				data:{    
					province : $('#province').val(),
				},
				type:'post',    
				cache:false,    
				dataType:'json',  
				success:function(data) {    
					if(data.success){
						$('#city').html(data.return_html);
						// $('#search-city-result').html(data.return_html);
					}
				 },    
				 error : function() {    
					 alert('<?php echo $this->__('Some Error'); ?>');
				 }    
			});
			
		});
	
	
		$('#store .action button').click(function(){
			$.ajax({
				url:'<?php echo $this->getUrl('storemap/index/getResultByCity'); ?>',
				data:{    
					province : $('#province').val(),
					city : $('#city').val(),
				},
				type:'post',    
				cache:false,    
				dataType:'json',    
				success:function(data) {    
					if(data.success){
						setLocation("<?php echo $this->getUrl('storemap'); ?>");
					}
				 },    
				 error : function() {    
					 alert('<?php echo $this->__('Some Error'); ?>');
				 }    
			});
		});
	});
</script>