<div class="std star-nav">
<h2>近期明星合作</h2>

<ul>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star">
<img src="<?php echo $this->getSkinUrl('images/chenchenthumb.jpg') ?>"/>
<br/>
<h3>lily携手陈辰 诠释“正合适”时尚哲学</h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_2">
<img src="<?php echo $this->getSkinUrl('images/chenyanfeithumb.jpg') ?>"/>
<br/>
<h3>lily商务时装助力《杜拉拉之似水年华》</h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_3">
<img src="<?php echo $this->getSkinUrl('images/zhubothumb.jpg') ?>"/>
<br/>
<h3>主播也“疯狂”　爱上“刚刚好的时尚”</h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_4">
<img src="<?php echo $this->getSkinUrl('images/pengbothumb.jpg') ?>"/>
<br/>
<h3>昕薇专属模特彭勃，身着lily拍摄杂志大片</h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_5">
<img src="<?php echo $this->getSkinUrl('images/xinzithumb.jpg') ?>"/>
<br/>
<h3>馨子身穿lily连衣裙做客《美丽俏佳人》</h3>
</a>

</li>

</ul>


</div>