<div class="std star-nav">
<h2><?php echo $this->__('Recent Celebrity Cooperation')?></h2>

<ul>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star">
<img src="<?php echo $this->getSkinUrl('images/chenchenthumb.jpg') ?>"/>
<br/>
<h3><?php echo $this->__('Chen Chen in Lily as example of the “No More No Less” ')?></h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_2">
<img src="<?php echo $this->getSkinUrl('images/chenyanfeithumb.jpg') ?>"/>
<br/>
<h3><?php echo $this->__('Lily in the hot TV series “Lala’s Shining Days”')?></h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_3">
<img src="<?php echo $this->getSkinUrl('images/zhubothumb.jpg') ?>"/>
<br/>
<h3><?php echo $this->__('TV hosts fall for “No More No Less”')?></h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_4">
<img src="<?php echo $this->getSkinUrl('images/pengbothumb.jpg') ?>"/>
<br/>
<h3><?php echo $this->__('Model Peng Po wearing Lily for the Xinwei magazine”')?></h3>
</a>

</li>
<li>
<a href="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>star_5">
<img src="<?php echo $this->getSkinUrl('images/xinzithumb.jpg') ?>"/>
<br/>
<h3><?php echo $this->__('Xinzi wearing Lily in TV program “the Beauty”')?></h3>
</a>

</li>

</ul>


</div>