<?php $shipping_province = $this->getShippingProvince();?>
<?php  ?>
		<?php  ?>
		<div class="content-wrapper shipping-method">
<div class="content">
	
	<h2><?php echo $this->__('Shipping Method') ?></h2>
	<ul class="form-list">
		<li>	
			<div class="input-box">
				<label for="shop_mentioning"><?php //echo $this->__('Shop Mentioning') ?><?php echo $this->__('Store Picking Up, Free!')?></label>
				<input type="radio" name="shipping_method" value="shop_mentioning" id="shop_mentioning" class="input-text" title="店铺自取，免运费<?php //echo $this->__('Shop Mentioning') ?>" />
			</div>
		</li>
		<?php if ($this->canUseExpressShipping()): ?>
		<li>	
			<div class="input-box">
				<label for="express"><?php echo $this->__('Express with 1500 points') ?></label>
				<input type="radio" name="shipping_method" value="express" id="express" class="input-text" title="<?php echo $this->__('Express with 1500 points') ?>" />
			</div>
		</li>
		<?php else:?>
		<li>
			<div class="input-box">
				<label for="express"><?php echo $this->__('Express with 1500 points') ?>(<?php echo $this->__("Not enough points")?>)</label>
			</div>
		</li>
		<?php  endif;?>
	</ul>

	<div id="custom_address_con">
		
	</div>

	<div class="shipping_addition" style="display:none;">
		<div class="mentioning_shops">
			<ul class="form-list">
				<li>
					<?php $citys = $this->getCitys(); ?>
					<select name="store_city" id="store_city" class="required-entry">
						<option value=""><?php echo $this->__('Please Select City'); ?></option>
						<?php foreach($citys as $city): ?>
							<option value="<?php echo $city; ?>"><?php echo $city; ?></option>
						<?php endforeach; ?>
					</select>
				</li>
				<li>
					<select name="store_area" id="store_area" class="required-entry"><option value=""><?php echo $this->__('Please Select Area'); ?></option></select>
				</li>
				<li>
					<select name="store_store" id="store_store" class="required-entry"><option value=""><?php echo $this->__('Please Select Store'); ?></option></select>
				</li>
			</ul>			
		</div>
	</div>
</div>

<div class="content"><?php echo $this->__('Warm tips:')?><?php echo $this->__('As the quantity of the gift is changing all the time , exchanging result is only associated with the success status of the order.')?></div>
</div>

<script type="text/template" id="tpl_custom_address">
<div class="content-wrapper address-list">
	<div class="content">
	<div class="express_addition">
			<h2><?php echo $this->__('Receiver Info') ?></h2>
			<ul class="form-list">
				<?php if ($this->customerHasAddresses()): ?>
					<li class="wide">
						<label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
						<div class="input-box">
							<?php echo $this->getAddressesHtmlSelect('points') ?>
						</div>
					</li>
				<?php endif; ?>
				 <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
						<ul>
							<li>
								<label class="required" for="reveiver_name"><em>*</em><?php echo $this->__('Receiver Name'); ?></label>
								<div class="input-box">
									<input type="text" name="reveiver_name" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="reveiver_name" class="input-text required-entry" title="<?php echo $this->__('Real Name') ?>" />
								</div>
							</li>
							
							<li>
								<label class="required" for="reveiver_tel"><em>*</em><?php echo $this->__('Reveriver Telphone'); ?></label>
								<div class="input-box">
									<input type="text" name="reveiver_tel" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="reveiver_tel" class="input-text required-entry" title="<?php echo $this->__('Real Name') ?>" />
								</div>
							</li>
							
							<li>
								<label class="required"><?php echo $this->__('Address'); ?></label>
								<select name="ship_province" id="ship_province" class="required-entry">
									<option value=""><?php echo $this->__('Please Select Province'); ?></option>
									<?php foreach($shipping_province as $_province):?>
									<option value="<?php echo $_province['province_id']; ?>"><?php echo $_province['province']; ?></option>
									<?php endforeach; ?>
								</select>
								<select name="ship_city" id="ship_city" class="required-entry">
									<option value=""><?php echo $this->__('Please Select City'); ?></option>
								</select>
								<textarea name="ship_address" class="required-entry" rows="6" cols="5"></textarea>
								
							</li>
							<li>
								<label class="required" for="reveiver_zip"><em>*</em><?php echo $this->__('Reveriver Zipcode'); ?></label>
								<div class="input-box">
									<input type="text" name="reveiver_zip" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="reveiver_zip" class="input-text required-entry" title="<?php echo $this->__('Reveriver Zipcode') ?>" />
								</div>
							</li>
							
							<li class="control">
								<input type="checkbox" name="save_address_book" id="save_address_book" value="1"><label for="save_address_book" class="checkbox" ><?php echo $this->__('存在地址薄') ?></label>
							</li>
						</ul>
				 </li>
			</ul>
		</div>
	</div>
</div>
</script>

<script type="text/javascript">
	jQuery(document).ready(function($){
	
		$('input[type="radio"][name="shipping_method"]').click(function(){
			if($(this).val() == "shop_mentioning"){
				$('.shipping_addition').show();
				$("#custom_address_con").html("");
				// 更新points
				if ($(".points-total").hasClass("added")) {
					var total = parseInt($(".points-total").html())  - 1500;
					$(".points-total").html(total);
					$(".points-total").removeClass("added")
				}
			}else {
				$('.shipping_addition').hide();
				$(".address-list").removeClass("hideme");
				$("#custom_address_con").append($("#tpl_custom_address").html());

				// 更新points
				var total = parseInt($(".points-total").html()) + 1500;
				$(".points-total").html(total);
				$(".points-total").addClass("added");
			}
		});
	
		
		$('#ship_province').live("change", function () {
			$.ajax({
				url: '<?php echo $this->getUrl('points/checkout/PvToCity'); ?>',
				data:{ pv : $(this).val()},
				type:'post',    
				cache:false,    
				dataType:'json', 
				success:function(data) {    
					if(data.success){
						$('#ship_city').html(data.html);
					}
				},
				 error : function() {    
					 alert('Some Error');
				 }   
			});
		});
		
		$('#ship_city').change("change" ,function(){
			$.ajax({
				url: '<?php echo $this->getUrl('points/checkout/CToArea'); ?>',
				data:{ c : $(this).val()},
				type:'post',    
				cache:false,    
				dataType:'json', 
				success:function(data) {    
					if(data.success){
						$('#ship_area').html(data.html);
					}
				},
				 error : function() {    
					 alert('Some Error');
				 }   
			});
		
		});
		
		
		$('.mentioning_shops select').change(function(){
			var current_elm = $(this).attr('id');
			var city = $('#store_city').val();
			var area = $('#store_area').val();
			if(current_elm != "store_store"){
				PostAjax(current_elm, city, area);
			}
			
		});

        $('#points-address-select').live('change',function(){
            if($(this).val() != ""){
                $('#billing-new-address-form').hide();
            }else{
                $('#billing-new-address-form').show();
            }
        });
	
	});
	function PostAjax(elm, city, area)
		{
			jQuery.ajax({
				url: '<?php echo $this->getUrl('points/checkout/ajax'); ?>',
				data:{
						current_elm : elm,
						city : city,
						area : area
					},
				type:'post',    
				cache:false,    
				dataType:'json',  
				success:function(data) {    
					if(data.success){
						jQuery('#store_' + data.target).html('');
						jQuery('#store_' + data.target).html(data.html);
					}
				},
				 error : function() {    
					 alert('Some Error');
				 }   
			});
		
		}

</script>

