

<script>
jQuery.noConflict();
jQuery(document).ready(function($){
	//$('.wrapper').addClass('is-right');
$('#back-button a').attr("href","<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>#vision");
	$('#back-button').click(function(){
		$('#loading').show();
		$('.wrapper').attr("style","");
		setTimeout(function() {
			  $('body .wrapper').addClass('move-right');
		}, 10);
	})
	
});
</script>