<div class="page page_club">
        <!-- <p class="club_ecoupon_txt">For system reason,  E coupon information will be synchronized after 24 hours later. </p> -->
        <div class="club_ecoupon_center cs-clear">
    

            <?php echo $this->getChildHtml("lily_customer_nav")?>

            <div class="club_tit  club_login_tit">
                <h2><?php echo $this->__('VIP CARD TERMS') ?></h2>
            </div>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('club-rule')->toHtml(); ?>
        </div>
</div>