<?php echo $this->getChildHtml("lily_customer_nav")?>

<div class="points_checkout">
	<div class="form-before">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout_progress')->toHtml(); ?>
		<div class="clear"></div>
	</div>

<div class="ponts_checkout_sucessed">
	<?php echo $this->__('Your order has been received.') ?>
	
<br/>
<br/>
<button onclick="setLocation('<?php echo $this->getUrl('giftproducts.html')?>')" class="button btn-continue" title="继续兑换" type="button"><span><span><?php echo $this->__('Gift Exchaning Page')?></span></span></button>
</div>


<?php Mage::getSingleton('core/session')->unsPointsSucceed(); ?>

	<div class="instruction">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('instruction')->toHtml(); ?>
	
	</div>
</div>