<?php $current_url = Mage::helper('core/url')->getCurrentUrl(); ?>
<div id="video">


<video id="lily-video1"  width="1280" height="720" controls  poster="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/video.jpg">
	<source src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/video/FF_LILY_20130815_VIDEO_PHONE_V1.webm" type="video/webm; codecs=vp8,vorbis" />
	<source src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/video/FF_LILY_20130815_VIDEO_PHONE_V1.mp4" type="video/mp4"  />
您的当前的浏览器可能不支持html5视频播放器

</video>
<video id="lily-video3"  width="1280" height="720"  controls>
	<source src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/video/LILY_MAKING_OF_MASTER.webmhd.webm" type="video/webm; codecs=vp8,vorbis" />
	<source src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/video/LILY MAKING OF MASTER.webmhd.mp4" />
您的当前的浏览器可能不支持html5视频播放器
</video>
<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function($){


$('#video-img').click(function(){
	$(this).hide();
	$("#lily-video1").show();
	$("#lily-video1").get(0).play();
	$("#lily-video1").get(0).play();
});
//$("#lily-video1").hide();

$("#lily-video1").bind("ended", function() {
	$(this).hide();
	$("#lily-video3").show();
	$("#lily-video3").get(0).play();
});

$("#lily-video3").bind("ended", function() {
	$(this).hide();
	$("#lily-video1").show();
	//$("#lily-video1").get(0).play();
});
});
</script>
</div>
<div id="kv" class="window">

<div class = 'container'>
			
			<div class = 'iosSlider'>
			
				<div class = 'slider'>

					<div class = 'item' dataurl = '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'>
					
						<span class="text1">F/W 2003 1/3</span>
						<img src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/kv/homepage_banner_1.jpg"/>
					</div>
					<div class = 'item' dataurl = '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'>
						<span class="text1">F/W 2003 1/3</span>
						<img src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/kv/homepage_banner_2.jpg"/>
					</div>
					<div class = 'item' dataurl = '<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>'>
						<span class="text1">F/W 2003 1/3</span>
						<img src="<?php Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>media/wysiwyg/kv/homepage_banner_3.jpg"/>
					</div>

				
				</div>
				
				<div class = 'prevContainer'>
					<div class = 'prev'>Prev slide</div>
				</div>
				
				<div class = 'nextContainer'>
					<div class = 'next'>Next slide</div>
				</div>
				
				<div class = 'selectorsBlock'>
				
					<div class = 'selectors'>
						<div class = 'item first selected'></div>
						<div class = 'item'></div>
						<div class = 'item'></div>

					</div>
					
				</div>
					
					
			
			</div>
			
				<!-- Add Jia This Share -->
			<div class="share-slider" onmouseover="setShare('','', '');">                 
			
		
			
				<div id="ckepop" class="ckepop">      
				
				<div id="open-share" class="open-share">
					<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
				</div>
				<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
				<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
				</div>
		
			</div>
		<!-- End -->
						
		</div>


</div>

<div id="brand"  class="window">
<div class="brand-txt" id="movetxt">
<!-- Add Jia This Share -->
		<div onmouseover="setShare('品牌故事', '<?php echo $current_url; ?>', '', '现代艺术范儿，是Lily品牌的创作之源。设计师将现代艺术与民俗、摩登时代、超现实主义、拜占庭艺术等潮流趋势相结合，创造出独特的OL商务时尚。');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open_b.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo_b.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent_b.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
<h2>Brand</h2>

<h3>品牌故事</h3>

<p>现代艺术范儿，是Lily品牌的创作之源。设计师将现代艺术与民俗、摩登时代、超现实主义、拜占庭艺术等潮流趋势相结合，创造出独特的OL商务时尚。</p>
<p>将“现代艺术范”作为创作源泉，Lily一跃成为众多职场女性的首选，坚持时尚与商务的完美融合，致力于打造具有现代艺术范儿的商务时装，生动地演绎着年轻女孩的梦想。</p>
<p>年轻OL的商务时装，可能太严肃，可能太时髦，然而她们始终向往着充满现代感、简单、随和、没有压力并富有乐趣的生活，Lily这样的时装却是正合适她们。</p>

<h3>集团简介</h3>

<p>上海丝绸集团品牌发展有限公司开创的女装品牌Lily诞生于2000年5月。作为商务时装的典范，Lily秉承时尚与商务完美结合的理念，以其清新优雅、简约流畅的风格，吸引着无数自信、优雅、独立的都市OL女性。Lily已成功登陆国际米兰时装周、德国CPD等多个国际性时尚盛会，并在米兰时装周上捧回“新锐设计师”大奖，成为国际时尚圈最受关注的新锐时装品牌。</p>
<p>自成立之日起，Lily在国内开设店铺500余家，店铺足迹遍及全国220多个城市，并成功进驻俄罗斯、沙特、泰国、马来西亚等海外国家，海外开设店铺逾50家。每季新款保持与欧美时尚圈同步。Lily正努力成为全球一线的少淑商务时装品牌！</p>

</div>
</div>

<div id="vision"  class="window">
	<div class="left zoom grid-9">
		<img src="<?php echo $this->getSkinUrl('images/vision-zoom.jpg') ?>"/>
		
		<!-- Add Jia This Share -->
		<div onmouseover="setShare('形象大片', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/vision-zoom.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
	
	</div>
	<div class="right grid-3">
		<div class="copy">
			<div class="copy-inner">
				<a href="fashion-video.html" class="link1">形象大片</a>
				<a href="look-book.html" class="link2">街拍look</a>
			</div>
		</div>
		<div class="move-right-img">
		<!-- Add Jia This Share -->
		<div onmouseover="setShare('街拍look', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/vision-moveright.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
			<img src="<?php echo $this->getSkinUrl('images/vision-moveright.jpg') ?>"/>
		</div>
	</div>


</div>
<div id="new"  class="window">
	<div class="left grid-6">
		<div class="grid-3 move-right-img">
			<!-- Add Jia This Share -->
		<div onmouseover="setShare('潮流趋势', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/share_open.png') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
			<img src="<?php echo $this->getSkinUrl('images/new-moveright.jpg') ?>"/>
		</div>
		<div class="grid-3 copy">
			<div class="copy-inner">
				<a href="trend.html" class="link1">潮流趋势</a>
				<a href="collection/modern-times.html" class="link2">搭配推荐</a>
			</div>
		</div>
		<div class="grid-6">
		<!-- Add Jia This Share -->
		<img src="<?php echo $this->getSkinUrl('images/new-grid6.jpg') ?>"/>
		<div onmouseover="setShare('潮流趋势', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/new-grid6.jpg') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
		</div>
	</div>
	<div class="right grid-6 move-left-img">
	<!-- Add Jia This Share -->
		<div onmouseover="setShare('搭配推荐', '<?php echo $current_url; ?>', '<?php echo $this->getSkinUrl('images/share_open.png') ?>', '刚刚在Lily商务时装官网分享了一张图片，一起来看看吧');">                 
		
	
		
			<div id="ckepop" class="ckepop">      
			
			<div id="open-share" class="open-share">
				<img src="<?php echo $this->getSkinUrl('images/share_open.png') ?>"/>
			</div>
			<a class="jiathis_button_tsina"><img src="<?php echo $this->getSkinUrl('images/share_weibo.png') ?>"/></a>
			<a class="jiathis_button_tqq"><img src="<?php echo $this->getSkinUrl('images/share_tencent.png') ?>"/></a>
			</div>
	
		</div>
		<!-- End -->
		<img src="<?php echo $this->getSkinUrl('images/new-moveleft.jpg') ?>"/>
	</div>
</div>
<div id="shop-online"  class="window">
	
	<div class="grid-3 amazon">
		<a href="http://www.amazon.cn/s/ref=amb_link_29972252_1?ie=UTF8&bbn=2016156051&page=1&rh=n%3A2016156051%2Cp_4%3ALily%2Cp_6%3AA1AJ19PSB66TGU&pf_rd_m=A1AJ19PSB66TGU&pf_rd_s=left-7&pf_rd_r=00V891APNX8EYE00HZSJ&pf_rd_t=101&pf_rd_p=82503972&pf_rd_i=2016156051
" target="_blank">amazon</a>
	</div>
	<div class="grid-3 tmall">
		<a href="http://lilyfs.tmall.com/shop/view_shop.htm?spm=a1z10.3.w3-18294325231.3.lIUoip&scene=taobao_shop" target="_blank">tmall</a>
	</div>
	<div class="grid-3 jd">
		<a href="http://mall.jd.com/index-37792.html" target="_blank">jd</a>
	</div>
	<div class="grid-3 yintai">
		<a href="http://qijian.yintai.com/lily/index.shtml " target="_blank">yintai</a>
	</div>

</div>
<div id="club"  class="window">
	<div class="left grid-3">
	<?php echo $this->getChildHtml('customer_form_login_mini') ?>
	
	
	</div>
	<div class="right zoom grid-9">
		<img src="<?php echo $this->getSkinUrl('images/club-zoom.jpg') ?>"/>
		
		<div id="share-button">
			<img src="<?php echo $this->getSkinUrl('images/share_button.png') ?>"/>
		</div>
	
	</div>



</div>
<div id="store"  class="window">

	<div class="left grid-6">

	</div>
	<div class="right grid-6">
	<?php $_province = Mage::getSingleton('core/session')->getSprovince(); ?>
	<?php if($_province != ""):?>
	<?php $citys = Mage::helper('lilystoremap')->getAllCityByProvince($_province); ?>
	<?php endif; ?>
	<?php $provinces = Mage::helper('lilystoremap')->getAllProvince(); ?>
	<div class="store-search">
		<div class="by-detail">
		
			<h1><span>Store</span>门店</h1>
			<div class="input-box widther">
				<label><?php echo $this->__('Country'); ?></label>
				<div class="input-box">
					<select class="selected search-city">
						<option value=""><?php echo $this->__('中国'); ?></option>
					</select>
				</div>
			</div>
			
			<div class="input-box widther">
				<label><?php echo $this->__('Province'); ?></label>
				<div class="input-box">
					<select class="selected search-city" id="province">
						<option value="">请选择</option>
						<?php foreach($provinces as $province): ?>
							<option value="<?php echo $province; ?>" <?php if($_province == $province) echo "selected = 'select'"; ?>><?php echo $province; ?></option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>
			
			
			<div class="input-box widther">
				<label><?php echo $this->__('City'); ?></label>
				<div class="input-box">
					<select class="selected search-city" id="city">
						<?php if($_province != ""):?>
							<?php foreach($citys as $city): ?>
								<option value="<?php echo $city; ?>"><?php echo $city; ?></option>
							<?php endforeach; ?>
						<?php else:?>
							<option value="">请先选择省市</option>
						<?php endif; ?>
					</select>
				</div>
			</div>
			
			<div class="action">
				<button class="button" title="Submit" type="button"><span><span><?php echo $this->__('Go'); ?></span></span></button>
			</div>
		</div>
	</div>
	
	</div>

</div>
<div id="timeline"  class="window">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('timeline')->toHtml(); ?>
</div>
<script type="text/javascript">
	jQuery(document).ready(function($){
	
		$('#province').change(function(){
			$.ajax({
				url:'<?php echo $this->getUrl('storemap/index/getCitysByProvince')?>',
				data:{    
					province : $('#province').val(),
				},
				type:'post',    
				cache:false,    
				dataType:'json',  
				success:function(data) {    
					if(data.success){
						$('#city').html(data.return_html);
						// $('#search-city-result').html(data.return_html);
					}
				 },    
				 error : function() {    
					 alert('<?php echo $this->__('Some Error'); ?>');
				 }    
			});
			
		});
	
	
		$('#store .action button').click(function(){
			$.ajax({
				url:'<?php echo $this->getUrl('storemap/index/getResultByCity'); ?>',
				data:{    
					province : $('#province').val(),
					city : $('#city').val(),
				},
				type:'post',    
				cache:false,    
				dataType:'json',    
				success:function(data) {    
					if(data.success){
						setLocation("<?php echo $this->getUrl('storemap'); ?>");
					}
				 },    
				 error : function() {    
					 alert('<?php echo $this->__('Some Error'); ?>');
				 }    
			});
		});
	});
</script>