<?php
/**
  * Loewenstark_Newsletter
  *
  * @category  Loewenstark
  * @package   Loewenstark_Newsletter
  * @author    Mathis Klooss <m.klooss@loewenstark.de>
  * @copyright 2013 Loewenstark Web-Solution GmbH (http://www.loewenstark.de). All rights served.
  * @license     https://github.com/mklooss/Loewenstark_Newsletter/blob/master/README.md
  */
?>
<span id="unsubscribe-button">我要退订</span>


    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-unsubscribe-validate-detail" style="display:none;">
        <div class="block-content">
            <div class="form-subscribe-header form-unsubscribe-header">
                <label for="newsletter-unsubscribe"><?php //echo $this->__('Unsubscribe Our Newsletter:') ?>请输入您的E-mail:</label>
            </div>
            <div class="input-box">
               <input type="text" name="email" id="newsletter-unsubscribe" title="<?php echo $this->__('Unsubscribe Our Newsletter') ?>" class="input-text required-entry validate-email" />
				<div class="actions">
					<button type="submit" title="<?php echo $this->__('Unsubscribe') ?>" class="button"><span><span><?php echo $this->__('Unsubscribe') ?></span></span></button>
				</div>
			</div>

        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterUnsubscriberFormDetail = new VarienForm('newsletter-unsubscribe-validate-detail');
    //]]>
	
	jQuery.noConflict();
	jQuery(document).ready(function($){
		$('#unsubscribe-button').click(function(){
			$('#newsletter-unsubscribe-validate-detail').slideToggle()
		})
	});
    </script>

