111<div class="account-create">
	<div class="page-title">
        <h1><?php echo $this->__('Activate an Account') ?></h1>
    </div>

	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form action="<?php echo Mage::getUrl('lily/index/activatePost') ?>" method="post" id="form-validate">
		<div class="fieldset">
			<h2 class="legend"><?php echo $this->__('Activate') ?></h2>
			<ul class="form-list">
				<li>
                    <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text" name="telephone" id="telephone" value="" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />
                    </div>
                </li>
				<li>
                    <label for="activate_code" class="required"><em>*</em><?php echo $this->__('Activate Code') ?></label>
                    <div class="input-box">
                        <input type="text" name="activate_code" id="activate_code" value="" title="<?php echo $this->__('Activate Code') ?>" class="input-text required-entry" />
                    </div>
                </li>
				
			</ul>
		</div>
		<div class="buttons-set">
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo Mage::getUrl('customer/account/login') ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
		</div>
	</form>
</div>
 <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>